name: edemekong
description: My portfolio app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  flutter_riverpod: ^2.4.0

  # navigation
  go_router: ^10.1.2

  # local storage
  shared_preferences: ^2.2.0

  # utils
  intl: ^0.17.0
  url_launcher: ^6.1.11
  responsive_builder: ^0.7.0
  extended_image: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
